# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 053a4e44e235bd848f2c891c6524ceb5481fe78c0d02a9f6a4cd8fd5b4ef968f411d4260926d9f8368901ea4cb6f5fc73aef1d7509d3daf17fa0e240d82eabef

test:
  secret_key_base: 9b9f31586ff102ce8e40257d637e7967584d5727f3a43312e75fc27ab3d1a2eaac8e44fa54d4c1ee4dabf6900d664c60be4a9ae17026c073087e4c4dbd9c9133

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
